# This schema represents our sqlite database. The sql schema can be found here: https://github.com/WindhoverLabs/tlm_cmd_merger/tree/develop#schemas
# It is modeled after DWARF4 and XTCE.

commands:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      name:
        type: string
      command_code:
        type: integer
        min: 0
      message_id:
        type: integer
        min: 0
      nacro:
        type: string
      symbol:
        type: string
      module:
        type: string

configurations:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      name:
        type: string
      value:
        type: integer
        min: 0
      module:
        type: string

dimension_lists:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
      field_id:
        type: integer
      dim_order:
        type: integer # Some data formats(such as SQL) do not enforce order. The dim_order field can be used to determine
                      # order of each dimension of the array.
      upper_bound: # Inclusive. Arrays such as "int[2]" would have an upper bound of 2.
        type: integer
        min: 0

elfs:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      name:
        type: string
      checksum:
        type: integer
      date:
        type: datetime
      little_endian:
        type: boolean

enumerations:
  type: list
  schema:
    type: dict
    schema:
      symbol:
        type: string
      value:
        type: integer
      name:
        type: integer

events:
  type: list
  schema:
    type: dict
    schema:
      id: #TODO: This needs to be fixed in the merger
        type: integer
        min: 0
      event_id:
        type: integer
        min: 0
      name:
        type: string
      module:
        type: string

fields:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
      symbol:
        type: string
      name:
        type: string
      byte_offset:
        type: integer
        min: 0
      type:
        type: string
      little_endian:
        type: integer # This is a boolean; 1 means true; 0 means false.
      bit_size:
        type: integer
      bit_offset:
        type: integer

modules:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      name:
        type: string

performance_ids:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      name:
        type: string
      perf_id:
        type: integer
      module:
        type: string

symbols:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      elf:
        type: string
      name:
        type: string
      byte_size:
        type: integer
        min: 0

telemetry:
  type: list
  schema:
    type: dict
    schema:
      id:
        type: integer
        min: 0
      name:
        type: string
      message_id:
        type: integer
      macro:
        type: string
      symbol:
        type: string
      module:
        type: string