name: Run juicer tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          pip install cpp-coveralls==0.4.2
          sudo apt-get install libdwarf-dev
          sudo apt-get install libelf-dev
          sudo apt-get install libsqlite3-dev
          sudo apt-get install g++
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run tests
        run: make coverage
      - name: coveralls
        run:  |
          cd build
          coveralls

